spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: errors

jwt:
  access-token-expiration-time: 86400000
  secret: 2f2cbcfb5955e9f2ae796ee0988c3dbe15fb5446dc51df1f0244432b966b79de

logging:
  level:
    org.jungle.code_post : debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace